#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/V1__create_users_table.yaml
server:
  port: 8080

jwt:
  secret: QMXJ5e+VceqEj+erF7s1//xb6rkeGtVm8M2J8NRwYYA=
  expiration: 3600000 # 1 час в миллисекундах

logging:
  level:
    org.springframework.security: DEBUG
    com.example.bankcards: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs